config/routes.rb
Rails.application.routes.draw do
  resources :passwords, param: :token
  # Defines the root path route ("/")
  root "events#index"

  resources :tenants
  resources :events
  resources :matches
  resources :candidates do
    member do
      get   'thumb'
      get   'big_thumb'
    end
  end
  resources :miscs do
    collection do
      delete  :destroy_all_votes
    end
  end
  resources :rank_slots
  resources :ranks
  resources :match_candidates
  resources :stages do
    member do
      get   'show_vote'
      get   'qr'
    end
  end
  resources :users
  resources :votes do
    collection do
      get   :new
      post  :create
      get   :voted
    end
  end
  resource  :session

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many    :match_candidates,  -> { not_deleted }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to  :tenant
  has_many    :matches, -> { not_deleted }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to  :event
  belongs_to  :rank_slot
  belongs_to  :stage
  has_many    :match_candidates,  -> { not_deleted.joins(:candidate).
                                          where('candidates.deleted_at IS NULL') }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/match_candidate.rb
class MatchCandidate < ApplicationRecord
  belongs_to  :match
  belongs_to  :candidate
  has_many    :votes
end

app/models/rank.rb
class Rank < ApplicationRecord
  validates_presence_of   :name
  validates_uniqueness_of :name,  conditions: ->{ where('deleted_at IS NULL') },
                                  scope:       :rank_slot_id

  belongs_to  :rank_slot
  has_many  :votes
end

app/models/rank_slot.rb
class RankSlot < ApplicationRecord
  has_many  :ranks,       -> { not_deleted }
  has_many  :matches,     -> { not_deleted }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/stage.rb
# Stage is a group of matches which allow user to vote on multiple matches
# at the same time.
class Stage < ApplicationRecord
  has_many  :matches,       -> { not_deleted }

  before_validation :set_uniq_key

  validates_presence_of   :name
  validates_uniqueness_of :name
  validates_uniqueness_of :key

  private

  def set_uniq_key
    if self.key.blank?
      # set 64byte length [0-9a-z] random string
      x = ''
      64.times{ x += rand(36).to_s(36)}
      self.key  = x
    end
  end
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_many  :events,  -> { not_deleted }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::SecurePassword

  has_secure_password
  has_many  :sessions, dependent: :destroy
  has_many  :votes

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def is_guest?
    !admin
  end

  def already_voted?(stage)
    votes.joins(match_candidate: {match: :stage}).where(stage: {id: stage.id}).exists?
  end

  def errors
    super.tap {|errors| errors.delete(:password, :blank) if is_guest? }
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to  :user
  belongs_to  :match_candidate

  validates_uniqueness_of :match_candidate_id,  scope: [:user_id]
  validate :validate_stage_availability

  scope :score, -> {
    joins(match_candidate: [{match: :stage}, :candidate]).
    where('matches.deleted_at           IS NULL').
    where('stages.deleted_at            IS NULL').
    where('candidates.deleted_at        IS NULL').
    where('match_candidates.deleted_at  IS NULL').
    select('matches.name as m, candidates.name as c, sum(point) as score').
    group(:m, :c)
  }

  private

  def validate_stage_availability
    if !match_candidate&.match.stage.available
      errors.add(:base, :stage_is_not_available)
    end
  end
end

app/controllers/match_candidates_controller.rb
class MatchCandidatesController < ApplicationController
  before_action :set_match_candidate, only: %i[edit update destroy ]

  # GET /matches or /matches.json
  def index
    @list = MatchCandidate.not_deleted.joins(:match, :candidate).
                where('matches.deleted_at IS NULL').
                where('candidates.deleted_at IS NULL').
                order('matches.name', 'candidates.name')
  end

  # GET /matches/new
  def new
    @rec = MatchCandidate.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @rec = MatchCandidate.new(allowed_params)

    respond_to do |format|
      if @rec.save
        format.html { redirect_to_index_with_success }
        format.json { render :show, status: :created, location: @rec }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @rec.update(allowed_params)
        format.html { redirect_to_index_with_success }
        format.json { render :show, status: :ok, location: @rec }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @rec.update!(deleted_at: Time.now)

    respond_to do |format|
      format.html { redirect_to match_candidates_path, status: :see_other, notice: "MatchCandidate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_match_candidate
    @rec = MatchCandidate.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def allowed_params
    params.expect(match_candidate: [:match_id, :candidate_id])
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/match_candidates_helper.rb
module MatchCandidatesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/miscs_helper.rb
module MiscsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/stages_helper.rb
module StagesHelper
  def qrcode_tag(url)
    qr = ::RQRCode::QRCode.new(url)
    tag.div(class: 'w-full m-10') do
      qr.as_svg(
        viewbox:  '0 0 100 100'
      ).html_safe
    end
  end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/match_candidates/_form.html.erb
<%= form_with(model: rec, class: "contents") do |form| %>
  <%= render_messages(rec) %>
  <%= v_select(form, rec, :match_id,      Match.not_deleted.order(:name).map{|m| [m.name, m.id]}) %>
  <%= v_select(form, rec, :candidate_id,  Candidate.not_deleted.order(:name).map{|c| [c.name, c.id]}) %>

  <div class="inline">
    <%= form.submit class: v_button_class %>
  </div>
<% end %>

app/views/match_candidates/_rec.html.erb
  <td class="px-3">
    <%= rec.match.name %>
  </td>
  <td class="px-3">
    <%= image_tag(thumb_candidate_path(rec.candidate),
                   width: '50') %>
  </td>
  <td class="px-3">
    <%= rec.candidate.name %>
  </td>

app/views/match_candidates/edit.html.erb
<% content_for :title, v_i18n('edit_rec', rec: @rec.class.model_name.human) %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= v_i18n('edit_rec', rec: @rec.class.model_name.human) %></h1>

  <%= render "form", rec: @rec %>
  <%= link_to_index(match_candidates_path) %>
</div>

app/views/match_candidates/index.html.erb
<% content_for :title, "Match Candidates" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-3">
    <h1 class="font-bold text-4xl"><%= MatchCandidate.model_name.human %></h1>
    <%= link_to v_i18n('new'), new_match_candidate_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="match_candidates" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @list.any? %>
      <table class="text-md bg-white shadow-md rounded mb-4"">
        <thead>
          <tr class="bg-gray-100 mb-5 mt-5 h-[3rem]">
            <th><%= Match.model_name.human %></th>
            <th colspan=2><%= Candidate.model_name.human %></th>
            <th><%= v_i18n('actions') %></th>
          </tr>
        </thead>
        <tbody>
          <% @list.each do |rec| %>
            <tr id="<%= dom_id rec %>" class="border-b hover:bg-cyan-200">
              <%= render 'rec', rec: rec %>
              <%= render_index_actions(rec) %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="text-center my-10">No matche candidate found.</p>
    <% end %>
  </div>
</div>

app/views/match_candidates/new.html.erb
<% content_for :title, v_i18n('new_rec', rec: @rec.class.model_name.human) %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= v_i18n('new_rec', rec: @rec.class.model_name.human) %></h1>

  <%= render "form", rec: @rec %>
  <%= link_to_index(match_candidates_path) %>
</div>