config/routes.rb
Rails.application.routes.draw do
  resources :passwords, param: :token
  # Defines the root path route ("/")
  root "events#index"

  resources :tenants
  resources :events
  resources :matches
  resources :candidates do
    member do
      get   'thumb'
      get   'big_thumb'
    end
  end
  resources :miscs do
    collection do
      delete  :destroy_all_votes
    end
  end
  resources :rank_slots
  resources :ranks
  resources :match_candidates
  resources :stages do
    member do
      get   'show_vote'
      get   'qr'
    end
  end
  resources :users
  resources :votes do
    collection do
      get   :new
      post  :create
      get   :voted
    end
  end
  resource  :session

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many    :match_candidates,  -> { not_deleted }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to  :tenant
  has_many    :matches, -> { not_deleted }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to  :event
  belongs_to  :rank_slot
  belongs_to  :stage
  has_many    :match_candidates,  -> { not_deleted.joins(:candidate).
                                          where('candidates.deleted_at IS NULL') }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/match_candidate.rb
class MatchCandidate < ApplicationRecord
  belongs_to  :match
  belongs_to  :candidate
  has_many    :votes
end

app/models/rank.rb
class Rank < ApplicationRecord
  validates_presence_of   :name
  validates_uniqueness_of :name,  conditions: ->{ where('deleted_at IS NULL') },
                                  scope:       :rank_slot_id

  belongs_to  :rank_slot
  has_many  :votes
end

app/models/rank_slot.rb
class RankSlot < ApplicationRecord
  has_many  :ranks,       -> { not_deleted }
  has_many  :matches,     -> { not_deleted }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/stage.rb
# Stage is a group of matches which allow user to vote on multiple matches
# at the same time.
class Stage < ApplicationRecord
  has_many  :matches,       -> { not_deleted }

  before_validation :set_uniq_key

  validates_presence_of   :name
  validates_uniqueness_of :name
  validates_uniqueness_of :key

  private

  def set_uniq_key
    if self.key.blank?
      # set 64byte length [0-9a-z] random string
      x = ''
      64.times{ x += rand(36).to_s(36)}
      self.key  = x
    end
  end
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_many  :events,  -> { not_deleted }

  validates_presence_of   :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::SecurePassword

  has_secure_password
  has_many  :sessions, dependent: :destroy
  has_many  :votes

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def is_guest?
    !admin
  end

  def already_voted?(stage)
    votes.joins(match_candidate: {match: :stage}).where(stage: {id: stage.id}).exists?
  end

  def errors
    super.tap {|errors| errors.delete(:password, :blank) if is_guest? }
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to  :user
  belongs_to  :match_candidate

  validates_uniqueness_of :match_candidate_id,  scope: [:user_id]
  validate :validate_stage_availability

  scope :score, -> {
    joins(match_candidate: [{match: :stage}, :candidate]).
    where('matches.deleted_at           IS NULL').
    where('stages.deleted_at            IS NULL').
    where('candidates.deleted_at        IS NULL').
    where('match_candidates.deleted_at  IS NULL').
    select('matches.name as m, candidates.name as c, sum(point) as score').
    group(:m, :c)
  }

  private

  def validate_stage_availability
    if !match_candidate&.match.stage.available
      errors.add(:base, :stage_is_not_available)
    end
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_rank, only: %i[ show edit update destroy ]

  # GET /ranks or /ranks.json
  def index
    @list = Rank.not_deleted.joins(:rank_slot).
                order(rank_slot:  {name:   'ASC'},
                      weight:     'DESC')
  end

  # GET /ranks/1 or /ranks/1.json
  def show
  end

  # GET /ranks/new
  def new
    @rec = Rank.new
  end

  # GET /ranks/1/edit
  def edit
  end

  # POST /ranks or /ranks.json
  def create
    @rec = Rank.new(allowed_params)

    respond_to do |format|
      if @rec.save
        format.html { redirect_to_index_with_success }
        format.json { render :show, status: :created, location: @rec }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ranks/1 or /ranks/1.json
  def update
    respond_to do |format|
      if @rec.update(allowed_params)
        format.html { redirect_to_index_with_success }
        format.json { render :show, status: :ok, location: @rec }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranks/1 or /ranks/1.json
  def destroy
    @rec.update!(deleted_at: Time.now)

    respond_to do |format|
      format.html { redirect_to ranks_path, status: :see_other, notice: "Rank was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rank
    @rec = Rank.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def allowed_params
    params.expect(rank: [:rank_slot_id, :name, :weight])
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/miscs_helper.rb
module MiscsHelper
end

app/helpers/rank_slots_helper.rb
module RankSlotsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/stages_helper.rb
module StagesHelper
  def qrcode_tag(url)
    qr = ::RQRCode::QRCode.new(url)
    tag.div(class: 'w-full m-10') do
      qr.as_svg(
        viewbox:  '0 0 100 100'
      ).html_safe
    end
  end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ranks/_form.html.erb
<%= form_with(model: rec, class: "contents") do |form| %>
  <%= render_messages(rec) %>
  <%= v_select(       form, rec, :rank_slot_id, RankSlot.not_deleted.order(:name).map{|rs| [rs.name, rs.id]}) %>
  <%= v_text_field(   form, rec, :name) %>
  <%= v_number_field( form, rec, :weight) %>

  <div class="inline">
    <%= form.submit class: v_button_class %>
  </div>
<% end %>

app/views/ranks/_rank.html.erb
  <td class="px-3">
    <%= link_to(rec.name, url_for(id: rec.id, action: 'show'), class: "w-full sm:w-auto px-3.5 py-2.5 hover:underline font-medium mx-0.5") %>
  </td>
  <td class="px-3">
    <%= rec.weight %>
  </td>

app/views/ranks/_rec.html.erb
  <td class="px-3">
    <%= rec.rank_slot.name %>
  </td>
  <td class="px-3">
    <%= link_to(rec.name, url_for(id: rec.id, action: 'show'), class: "w-full sm:w-auto px-3.5 py-2.5 hover:underline font-medium mx-0.5") %>
  </td>
  <td class="px-3 text-right">
    <%= rec.weight %>
  </td>

app/views/ranks/edit.html.erb
<% content_for :title, v_i18n('edit_rec', rec: @rec.class.model_name.human) %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= v_i18n('edit_rec', rec: @rec.class.model_name.human) %></h1>

  <%= render "form", rec: @rec %>
  <%= link_to_index(ranks_path) %>
</div>

app/views/ranks/index.html.erb
<% content_for :title, "Ranks" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= Rank.model_name.human %></h1>
    <%= link_to v_i18n('new'), new_rank_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="ranks" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @list.any? %>
      <table class="text-md bg-white shadow-md rounded mb-4">
        <thead>
          <tr>
            <th><%= RankSlot.model_name.human           %></th>
            <th><%= v_i18n('name')                      %></th>
            <th><%= Rank.human_attribute_name('weight') %></th>
            <th><%= v_i18n('actions')                   %></th>
          </tr>
        </thead>
        <tbody>
          <% @list.each do |rec| %>
            <tr id="<%= dom_id rec %>" class="border-b hover:bg-cyan-200">
              <%= render 'rec', rec: rec %>
              <%= render_index_actions(rec) %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="text-center my-10">No ranks found.</p>
    <% end %>
  </div>
</div>

app/views/ranks/new.html.erb
<% content_for :title, v_i18n('new_rec', rec: @rec.class.model_name.human) %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= v_i18n('new_rec', rec: @rec.class.model_name.human) %></h1>

  <%= render "form", rec: @rec %>
  <%= link_to_index(ranks_path) %>
</div>

app/views/ranks/show.html.erb
<% content_for :title, "Showing rank" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing rank</h1>

  <%= render @rank %>

  <%= link_to "Edit this rank", edit_rank_path(@rank), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to ranks", ranks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to "Destroy this rank", @rank, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>